from iohblade.llm import LLM
from iohblade.method import Method
from iohblade.problem import Problem
from iohblade.solution import Solution

from iohblade.methods.moeh.prompts import MoEH_Prompts
from iohblade.methods.moeh.population import Population

class MoEH:
    def __init__(self,
                 llm: LLM,
                 problem: Problem,
                 iterations: int,
                 max_sample_nums: int,
                 population_size: int,
                 use_e2_operator: bool = True,
                 use_m1_operator: bool = True,
                 use_m2_operator: bool = True,
                 max_workers: int = 2) -> None:
        """
            A `Multi-Objective Evolution of Heuristic Using LLLM` implementation for BLADE, as defined in paper: https://arxiv.org/pdf/2409.16867

            ## Params:
            - `llm: LLM`: Object of one of the final class in `iohblade.llm`.
            - `problem: Problem`: Object instance of a class that inherits from `iohblade.problem`.
            - `iterations: int` Max number of iterations for which the algorithm is to be run.
            - `max_sample_nums: int`: Max number sample that can be generated by the LLM.
            - `population_size: int`: Population size (λ / µ) for the evolutionary algorithm.
            - `use_e2_operator: bool(True)`: Use e2 operation as stated in the `moeh.prompts`; multi-individuals -> 1 individual mutation.
            - `use_m1_operator: bool(True)`: Use m1 operation as stated in the `moeh.prompts`; 1 -> 1 mutation (adds novel methods.)
            - `use_m2_operator: bool(True)`: Use m1 operation as stated in the `moeh.prompts`; 1 -> 1 mutation (used different approach.)
            - `max_workers: int(2)`: Declaration of max `loky` workers for `joblib.Parallel`.

            ## Note:

            - The algorithm quits running when either of the conditons are met (||):
                - `iterations` count of generations are iterated over.
                - `max_sample_nums` count of samples are generated.
        """
        
        assert max_sample_nums > 1, "Max sample number must be positive integer."
        assert type(max_sample_nums) == int, "Max sample number must be positive integer."
        assert population_size > 1, "Population size must be positive integer."
        assert type(population_size) == int, "Population size must be positive integer."
        assert iterations > 1, "Iteration count must be positive integer."
        assert type(iterations) == int, "Iteration count must be positive integer."
        assert max_workers > 1, "Max Workers must be positive integer."
        assert type(max_workers) == int, "Max Workers must be positive integer."

        # Accepted parameters.
        self.llm = llm
        self.problem = problem
        self.iterations = iterations
        self.max_sample_nums = max_sample_nums

        self.max_sample_nums = max_sample_nums
        self.population_size = population_size
        self.iterations = iterations

        self.use_e2_operator = use_e2_operator
        self.use_m1_operator = use_m1_operator
        self.use_m2_operator = use_m2_operator

        config = self.problem.get_config()
        self.minimisation = config['minimisation']


        # Runtime parameters:
        self._current_iteration = 0
        self.population = Population(population_size)

    def initialise(self):
        """
            Initialises the evolutionary algorithm.

            # Params:
                - `None`

            # Returns:
                - Inline function, doesn't return anything, updates `self.population`.
        """
        prompt = MoEH_Prompts.get_prompt_i1(self.problem.task_prompt, 
                                            self.problem.example_prompt, 
                                            self.problem.format_prompt)
        
        #TODO: Parallel this.....
        while (len(self.population)  < self.population_size) and self.max_sample_nums > 0:
            individual = self.llm.sample_solution([prompt])
            individual = self.problem(individual)
            self.population.append(individual)
            self.max_sample_nums -= 1
        
    



