import random
import numpy as np
from enum import Enum

from iohblade.llm import LLM
from iohblade.method import Method
from iohblade.problem import Problem
from iohblade.solution import Solution

from iohblade.methods.moeh.prompts import MoEH_Prompts
from iohblade.methods.moeh.population import Population

class MutationType(Enum):
    E2 = 'e2'
    M1 = 'm1'
    M2 = 'm2'


class MoEH:
    def __init__(self,
                 llm: LLM,
                 problem: Problem,
                 iterations: int,
                 max_sample_nums: int,
                 population_size: int,
                 use_e2_operator: bool = True,
                 use_m1_operator: bool = True,
                 use_m2_operator: bool = True,
                 max_workers: int = 2) -> None:
        """
            A `Multi-Objective Evolution of Heuristic Using LLLM` implementation for BLADE, as defined in paper: https://arxiv.org/pdf/2409.16867

            ## Params:
            - `llm: LLM`: Object of one of the final class in `iohblade.llm`.
            - `problem: Problem`: Object instance of a class that inherits from `iohblade.problem`.
            - `iterations: int` Max number of iterations for which the algorithm is to be run.
            - `max_sample_nums: int`: Max number sample that can be generated by the LLM.
            - `population_size: int`: Population size (λ / µ) for the evolutionary algorithm.
            - `use_e2_operator: bool(True)`: Use e2 operation as stated in the `moeh.prompts`; multi-individuals -> 1 individual mutation.
            - `use_m1_operator: bool(True)`: Use m1 operation as stated in the `moeh.prompts`; 1 -> 1 mutation (adds novel methods.)
            - `use_m2_operator: bool(True)`: Use m1 operation as stated in the `moeh.prompts`; 1 -> 1 mutation (used different approach.)
            - `max_workers: int(2)`: Declaration of max `loky` workers for `joblib.Parallel`.

            ## Note:

            - The algorithm quits running when either of the conditons are met (||):
                - `iterations` count of generations are iterated over.
                - `max_sample_nums` count of samples are generated.
        """
        
        assert max_sample_nums > 1, "Max sample number must be positive integer."
        assert type(max_sample_nums) == int, "Max sample number must be positive integer."
        assert population_size > 1, "Population size must be positive integer."
        assert type(population_size) == int, "Population size must be positive integer."
        assert iterations > 1, "Iteration count must be positive integer."
        assert type(iterations) == int, "Iteration count must be positive integer."
        assert max_workers > 1, "Max Workers must be positive integer."
        assert type(max_workers) == int, "Max Workers must be positive integer."

        # Accepted parameters.
        self.llm = llm
        self.problem = problem
        self.iterations = iterations
        self.max_sample_nums = max_sample_nums

        self.max_sample_nums = max_sample_nums
        self.population_size = population_size
        self.iterations = iterations

        config = self.problem.get_config()
        self.minimisation = config['minimisation']


        # Runtime parameters:
        self._current_iteration = 0
        self.population = Population(population_size, self.minimisation)

        # Mutation Types
        self.allowed_mutation_types: list[MutationType] = []
        if use_e2_operator:
            self.allowed_mutation_types.append(MutationType.E2)
        if use_m1_operator:
            self.allowed_mutation_types.append(MutationType.M1)
        if use_m2_operator:
            self.allowed_mutation_types.append(MutationType.M2)

        assert len(self.allowed_mutation_types) >= 1, "Atleast one mutation type is expected, use_x_operator all set false in invalid state."

    def initialise(self):
        """
            Initialises the evolutionary algorithm.

            # Params:
                - `None`

            # Returns:
                - Inline function, doesn't return anything, updates `self.population`.
        """
        prompt = MoEH_Prompts.get_prompt_i1(self.problem.task_prompt, 
                                            self.problem.example_prompt, 
                                            self.problem.format_prompt)
        
        #TODO: Parallel this.....
        while (len(self.population)  < self.population_size) and self.max_sample_nums > 0:
            individual = self.llm.sample_solution([prompt])
            individual = self.evaluate(individual)
            self.population.append(individual)
            self.max_sample_nums -= 1
    
    def evaluate(self, individual: Solution):
        return self.problem(individual)
    
    def query_individual(self, type: MutationType, pop: list[Solution]) -> Solution:
        """
            Queries and returns a new LLM written solution using one of the MutationTypes.
        
            ## Parameters:
            - `type: MutationType`: Expects an enum typed `MutationType` to decide which prompt to use for an evolution.
            - `pop: list[Solution]`: Expects an array of solution of size 1 for `M1` and `M2` types, and of arbitrary size [1, n] for `E2`.

            ## Expectations:
            - For each `MutationType` following size of population is expected:
                - `M1`: 1
                - `M2`: 1
                - `E2`: [1, n]

            ## Returns:
            - `Solution`: an evolved solution generated by LLM using given pop and `MutationType`.
        """
        match(type):
            case MutationType.M1:
                prompt = MoEH_Prompts.get_prompt_m1(
                    self.problem.task_prompt, 
                    self.problem.example_prompt, 
                    self.problem.format_prompt, 
                    pop[0])
                solution = self.llm.sample_solution([prompt], parent_ids=[pop[0]])
                return solution
            case MutationType.M2:
                prompt = MoEH_Prompts.get_prompt_m2(self.problem.task_prompt, 
                    self.problem.example_prompt, 
                    self.problem.format_prompt, 
                    pop[0])
                solution = self.llm.sample_solution([prompt], parent_ids=[pop[0]])
                return solution

            case MutationType.E2:
                prompt = MoEH_Prompts.get_prompt_e2(self.problem.task_prompt, 
                    self.problem.example_prompt, 
                    self.problem.format_prompt, 
                    pop)
                solution = self.llm.sample_solution([prompt], parent_ids=[pop[i] for i in range(len(pop))])
                return solution

    def evolve_solution(self, population_index: int) -> Solution:
        mutation_type = random.choice(self.allowed_mutation_types)
        pop = self.population.population
        match(mutation_type):
            case MutationType.E2:
                solution = self.query_individual(mutation_type, pop)
            case _:
                solution = self.query_individual(mutation_type, [pop[population_index]])
        solution = self.evaluate(solution)
        self.max_sample_nums -= 1
        return solution
    
    def run(self) -> Solution:
        generation = 0
        new_population : list[Solution] = []

        self.initialise()
        while((self.iterations < generation) and (self.max_sample_nums > 0)):
            new_population = []
            self.population.parent_selection(self.population_size)
            for index in range(len(self.population.population)):
                new_individual = self.evolve_solution(index)
                new_population.append(new_individual)
            
            for individual in new_population:
                self.population.append(individual)
            
            _ = self.population.population_management()
        
        return self.population.get_best()
            
